[package]
name = "dungeon-breeder-core"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }