[package]
name = "dungeon-breeder-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
dungeon-breeder-core = { workspace = true }
eframe = { version = "0.32.1", features = ["persistence", "wgpu"] }
egui = { version = "0.32.1", features = ["persistence"] }
egui-notify = "0.20.0"
egui_extras = "0.32.1"
humantime = { workspace = true }
image = { version = "0.25.8", default-features = false, features = ["png"] }
serde = { workspace = true }
strum = { workspace = true }
